# Generated by Django 4.1.7 on 2023-03-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=120)),
                ('Day0', models.CharField(max_length=30)),
                ('Day1', models.CharField(max_length=30)),
                ('Day2', models.CharField(max_length=30)),
                ('Day3', models.CharField(max_length=30)),
                ('Day4', models.CharField(max_length=30)),
                ('Day5', models.CharField(max_length=30)),
                ('Day6', models.CharField(max_length=30)),
                ('Day7', models.CharField(max_length=30)),
            ],
        ),
    ]
